---
- hosts: all
  become: yes
  user: imsalyunus
  tasks:
    - name: Install server asterisk (state=present is optional)
      ansible.builtin.apt:
        name: asterisk
        state: present
    - name: Hapus file default file sip.conf & extension.conf
      ansible.builtin.file:
        path: /etc/asterisk/extension.conf
        path: /etc/asterisk/sip.conf
        state: absent
    - name: Download file custom sip.conf, extension.conf, restart.sh
      git:
        repo: https://github.com/imsalyunus/asterisk.git
        dest: /etc/asterisk/data/
        clone: yes
        update: yes
    - name: Copy file sip.conf ke folder asterisk
      copy: remote_src=True src=/etc/asterisk/data/sip.conf dest=/etc/asterisk
    - name: Copy file extension.conf ke folder asterisk  
      copy: remote_src=True src=/etc/asterisk/data/extension.conf dest=/etc/asterisk
    - name: Copy file restart.sh ke folder asterisk  
      copy: remote_src=True src=/etc/asterisk/data/restart.sh dest=/etc/asterisk  
    - name:
      ansible.builtin.shell: restart.sh >> restart.sh
