---
- name: Download file
  hosts: all
  vars:
    repo: "git@github.com:imsalyunus/asterisk.git"
    dest: "/etc/asterisk"
  tasks:
    - name: download
      ansible.builtin.yum:
        name: git
        states: present
