---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Ngecek Log Server
      shell: tail -f /var/log/syslog

    - name: Hentikan perintah tail -f
      shell: pkill -f "tail -f /var/log/syslog"
      ignore_errors: yes
