---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Install Zabbix repository
      apt:
        deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-2+ubuntu22.04_all.deb
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix server
      apt:
        name: zabbix-server-mysql
        state: present

    - name: Configure Zabbix Server database password
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: 'admin'
        line: 'admin'

    - name: Restart Zabbix Server
      systemd:
        name: zabbix-server
        state: restarted
        enabled: yes
