---
- hosts: all
  become: yes
  user: upb
  tasks:
    - name: This command will only run when file_to_check.txt doesn't exist
      ansible.builtin.shell: tail -n 999999999999999 /var/log/syslog | grep "$(date + '%b %d')"
 >> "Log_$(date +'%Y%m%d').txt"
      args:
        creates: file_to_check.txt
        
    - name: Display list of files in /var/log
      ansible.builtin.command: cat "Log_$(date +'%Y%m%d').txt"
      
