---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Ngecek Log Server
      command: tail -f /var/log/syslog

    - name: Hentikan perintah tail -f
      command: pkill -f "tail -f /var/log/syslog"
      ignore_errors: yes
