---
- hosts: all
  become: yes
  user: upb
  tasks:
    - name: Menyimpan log server pada saat tanggal saat ini
      ansible.builtin.shell: tail -n 999999999999999 /var/log/syslog | grep "$(date + '%b %d')"
 >> "Log_$(date +'%Y%m%d').txt"
      args:
        creates: file_to_check.txt
        
    - name: Display list of files in /var/log
      ansible.builtin.command: cat "Log_$(date +'%Y%m%d').txt"
      
