---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Mengecek status asterisk
      debug:
        msg: "Asterisk is {{ 'not ' if asterisk_status.stdout_lines[0] == 'Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)' else '' }}running."
      shell: asterisk -rx "core show uptime"
      register: asterisk_status
    - name: Melihat user yang aktif
      shell: asterisk -rx 'sip show peers'
      register: active_users
      debug:
        var: active_users.stdout_lines
    
    
   
