---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Get list of active users on Asterisk
      shell: asterisk -rx 'sip show users'
      register: active_users
    - name: Show list of active users on Asterisk
      debug:
        var: active_users.stdout_lines
    - name: Get IP addresses of active users on Asterisk
      set_fact:
        active_user_ips: "{{ active_users.stdout_lines | select('match', '^\\d+\\s+') | map('split', ' :') | map('last') | map('split', '@') | map('first') | list }}"
    - name: Show IP addresses of active users on Asterisk
      debug:
        var: active_user_ips
