---
- hosts: all
  become: yes
  user: upb
  tasks:
    - name: Melihat berapa lamanya waktu asterisk berjalan
      shell: asterisk -rx "core show uptime"
      register: asterisk_status
    - name: Mengecek status asterisk aktif atau tidak
      debug:
        msg: "Asterisk is {{ 'not ' if asterisk_status.stdout_lines[0] == 'Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)' else '' }}running."
    - name: Melihat user yang aktif
      shell: asterisk -rx 'sip show peers'
      register: active_users
    - name: Menampilkan user yang aktif
      debug:
        var: active_users.stdout_lines
