---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Get list of active users on Asterisk
      shell: asterisk -rx 'sip show users'
      register: active_users
    - name: Show list of active users on Asterisk
      debug:
        var: active_users.stdout_lines
