---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Get active users
      shell: asterisk -rx 'sip show peers'
      register: active_users
    - name: Show list of active users on Asterisk
      debug:
        var: active_users.stdout_lines
    - name: Get Asterisk status
      shell: asterisk -rx "core show uptime"
      register: asterisk_status
    - name: Print Asterisk status
