
---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Shut down a machine with shutdown command in unusual place
      community.general.shutdown:
        search_paths:
         - '/usr/sbin/shutdown now'
