---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: Server test
      hosts: ism
      connection: local
      gather_facts: no
      vars:
        ism:
          host: "192.168.243.83"
          username: "administrator"
          password: "admin"

  tasks:
    - name: "Get server status information"
      inspur.sm.server_info:
        provider: "ism"
