---
- hosts: all
  become: yes
  user: administrator
  tasks:
    - name: collect facts about system services
      service_facts:
      register: services_state

    - name: Debug
      debug:
      var: services_state
